'03-2-invert-objects' and '04-1-column-chart'
js-tasks-ru/js-20200928_zh-zhyrov pull request #3
Opened 2020-10-11 19:41 UTC by zzzhyrov

2020-10-11 19:47 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have property 'chartHeight
+ should render data correctly
+ should have ability to be updated by new "data" values (should re-render only body with charts columns)
+ should have loading indication if data wasn't passed 
+ should have ability to be removed
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-12 12:10 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        let maxValue = Math.max(...this.data);
проверьте изменяете ли вы значение `maxValue` и исправьте по результату проверки объявление данной переменной

2020-10-12 12:11 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +            columns = (this.data)
почему бы не сделать присвоение `this.data` в момент объявления переменной `columns`?
И второй вопрос: почему бы сразу не итерировать `this.data`? зачем создавать дополнительную переменную `columns` со значением пустой строки, хотя по факту там будет хранится массив?

2020-10-12 12:12 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +            .map(function(item) {
В колбеках таких методов как `map`, `reduce`, `forEach` принято использовать стрелочные функции

2020-10-12 12:17 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        let column_chart = document.createElement('div');
здесь что-то произошло с подходом к именованию переменных. До этого момента по коду использовалось именование под названием "camelCase", в строке 37 используется именование "snake_case". Смешивать подходы к именованию - плохая практика.

2020-10-12 12:18 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        this.chartHeight = 50;
объявление и присвоение статических значений, которые не будут изменяться по коду, лучше производить в `constructor` - тогда все такие значения будут находится в одном месте и будут доступны всем другим методам

2020-10-12 12:19 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +    destroy() {
пустых методов не должно быть в решениях.

2020-10-12 12:19 UTC, dosandk requested changes
необходимо исправить решение `ColumnChart` согласно комментариям

2020-10-17 13:42 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-10-17 13:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-18 16:39 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +        let key = obj[value];
`key` - это `const`

2020-10-18 16:40 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    } else {
этот код можно вынести за пределы `else` и избавиться от данного блока, так как `return` оборвет выполнения функции

2020-10-18 16:41 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        let size = this.chartHeight / maxValue;
`size` - это `const`

2020-10-18 16:42 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        if (this.data.length) {
данную конструкцию лучше заменить на тернарное выражение

2020-10-18 16:42 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        let columnChart = document.createElement('div');
`columnChart` - это `const`

2020-10-18 16:42 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +        // console.log(NotificationMessage.flag);
закомментированного кода не должно быть в PR

2020-10-18 16:43 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +        this.textMessage = textMessage || '';
почему бы нам не добавить дефолтное значение для `textMessage` прямо в аргументах конструктора?

2020-10-18 16:44 UTC, dosandk approved these changes
решения принимаю, но напомните мне пожалуйста в каких случаях мы используем `const` а в каких `let` при объявлении переменных?

2020-10-18 16:44 UTC, merged

2020-10-18 16:55 UTC, zzzhyrov commented
> решения принимаю, но напомните мне пожалуйста в каких случаях мы используем `const` а в каких `let` при объявлении переменных?

`const` закладываем в случаях, если мы знаем, что пременную далее не нужно изменять.
`let` - наоборот, используем в случаях последуюещего переопределения.

Виноват, исправлю и запушу. Пул реквест уже создавать не нужно?